# Preprocessing Steps

## 1 Business Understanding

## 2 Data Understanding

## 3 Drop non-intersted features

## 4 Check Data types

## 5 Handle Data types

## 6 Check Nulls

## 7 Handle Nulls

## 8 Check Outliers

## 9 Handle Outliers

## 10 Check dublicated

## 11 Handle dublicated

## 12 Data Visualization

## 13 Data splitting

## 14 Normalization

## 15 Encoding

# Business and Data Understanding

In [1]:
import pandas as pd

In [33]:
df = pd.read_csv('Titanic.csv')

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
type(df)

pandas.DataFrame

# Drop unneeded data

In [ ]:
#unnecessary columns
# axis to specify that we want to drop columns (axis=1) rather than rows (axis=0)
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [34]:
from config import COLS_DROP
from preprocessing import drop_columns

df = drop_columns(df, COLS_DROP)

In [35]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

# Check Data types

In [22]:
dtypes = df.dtypes
print(dtypes)

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [ ]:
#this gives us the number of unique values in each column
df.nunique()

Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [25]:
pd.DataFrame({'dtypes': dtypes, 'unique': df.nunique()}).T

       Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
dtypes    int64  int64  str  float64  int64  int64  float64   str      str
unique        2      3    2       88      7      7      248   147        3

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    str
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 62.8 KB

# Handle Data types

In [46]:
cat_cols = ["Survived", "Pclass", "Sex", "Embarked" , "SibSp", "Parch"]
df[cat_cols] = df[cat_cols].astype('category')

In [47]:
dtypes = df.dtypes
print(dtypes)
df.nunique()
pd.DataFrame({'dtypes': dtypes, 'unique': df.nunique()}).T

Survived    category
Pclass      category
Sex         category
Age          float64
SibSp       category
Parch       category
Fare         float64
Cabin            str
Embarked    category
dtype: object

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
unique,2,3,2,88,7,7,248,147,3

In [39]:
def get_type_info(df):
    return pd.DataFrame({'dtypes': df.dtypes, 'unique': df.nunique()}).T

In [48]:
get_type_info(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,str,category
unique,2,3,2,88,7,7,248,147,3

In [49]:
df.select_dtypes('category')

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
886        0      2    male     0     0        S
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[891 rows x 6 columns]

# Check and Handle Nulls

In [50]:
df.info

<bound method DataFrame.info of     Survived Pclass     Sex   Age SibSp Parch     Fare Cabin Embarked
0          0      3    male  22.0     1     0   7.2500   NaN        S
1          1      1  female  38.0     1     0  71.2833   C85        C
2          1      3  female  26.0     0     0   7.9250   NaN        S
3          1      1  female  35.0     1     0  53.1000  C123        S
4          0      3    male  35.0     0     0   8.0500   NaN        S
..       ...    ...     ...   ...   ...   ...      ...   ...      ...
886        0      2    male  27.0     0     0  13.0000   NaN        S
887        1      1  female  19.0     0     0  30.0000   B42        S
888        0      3  female   NaN     1     2  23.4500   NaN        S
889        1      1    male  26.0     0     0  30.0000  C148        C
890        0      3    male  32.0     0     0   7.7500   NaN        Q

[891 rows x 9 columns]>

In [52]:
df.isnull()

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [53]:
df

    Survived Pclass     Sex   Age SibSp Parch     Fare Cabin Embarked
0          0      3    male  22.0     1     0   7.2500   NaN        S
1          1      1  female  38.0     1     0  71.2833   C85        C
2          1      3  female  26.0     0     0   7.9250   NaN        S
3          1      1  female  35.0     1     0  53.1000  C123        S
4          0      3    male  35.0     0     0   8.0500   NaN        S
..       ...    ...     ...   ...   ...   ...      ...   ...      ...
886        0      2    male  27.0     0     0  13.0000   NaN        S
887        1      1  female  19.0     0     0  30.0000   B42        S
888        0      3  female   NaN     1     2  23.4500   NaN        S
889        1      1    male  26.0     0     0  30.0000  C148        C
890        0      3    male  32.0     0     0   7.7500   NaN        Q

[891 rows x 9 columns]

In [64]:
# How many null values are there in each column?
null = df.isnull().sum()
ratio = null / len(df) * 100
ratio

Survived    0.0
Pclass      0.0
Sex         0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
Embarked    0.0
dtype: float64

In [ ]:
# Remove rows with missing values in the 'Embarked' column
df = df.dropna(subset=['Embarked'])

In [58]:
df = df.drop("Cabin", axis=1 )

In [63]:
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age , inplace=True)

/tmp/ipykernel_1663/3924196385.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(median_age , inplace=True)

In [65]:
pd.DataFrame({'null': df.isnull().sum(), 'ratio': df.isnull().sum() / len(df) * 100}).T

       Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
null        0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
ratio       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

# Outliers

<img src="/home/mohamed_hisham/AI/ML-DEPI/src/DA/Session-3/code/Outiler-Boxplot.webp" alt="Outliers and IQR" width="1000">

In [68]:
num_col = df.select_dtypes('number').columns
for col in num_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    print(f"Column: {col}, Q1: {Q1}, Q3: {Q3}")
    IQR = Q3 - Q1
    print(f"Column: {col}, IQR: {IQR}")
    lower_fence = Q1 - 1.5 * IQR
    print(f"Column: {col}, Lower Fence: {lower_fence}")
    upper_fence = Q3 + 1.5 * IQR
    print(f"Column: {col}, Upper Fence: {upper_fence}")

Column: Age, Q1: 22.0, Q3: 35.0
Column: Age, IQR: 13.0
Column: Age, Lower Fence: 2.5
Column: Age, Upper Fence: 54.5
Column: Fare, Q1: 7.8958, Q3: 31.0
Column: Fare, IQR: 23.1042
Column: Fare, Lower Fence: -26.7605
Column: Fare, Upper Fence: 65.6563

In [67]:
df.describe()

              Age        Fare
count  889.000000  889.000000
mean    29.315152   32.096681
std     12.984932   49.697504
min      0.420000    0.000000
25%     22.000000    7.895800
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200