# Numpy

In [1]:
import numpy as np

x = np.array([1, 2, 3])
x.shape

(3,)

In [ ]:
def convert_dtype(arr, new_dtype):
    """
    Convert the data type of a NumPy array to a new data type.

    Parameters:
    arr (numpy.ndarray): The input NumPy array.
    new_dtype (data-type): The desired data type to convert to.

    Returns:
    numpy.ndarray: A new NumPy array with the specified data type.
    """

    try:
        arr = np.asarray(arr)  
        return arr.astype(new_dtype)
    except Exception as e:
        raise TypeError(f"invalid target data type {new_dtype}") from e
    except Exception as e:
        raise ValueError(f"cannot convert array to {new_dtype}") from e

In [4]:
list1 = [1, 2, 3, 4, 5]

In [5]:
convert_dtype(np.array(list1), np.float64)

array([1., 2., 3., 4., 5.])

In [ ]:
def check_dtype(arr, expected_dtype):
    """
    Check if the data type of a NumPy array matches the expected data type.

    Parameters:
    arr (numpy.ndarray): The input NumPy array.
    expected_dtype (data-type): The expected data type to check against.

    Returns:
    bool: True if the data type matches, False otherwise.
    """

    try:
        if not isinstance(arr, np.ndarray):
            raise TypeError("Input must be a NumPy array.")
        return arr.dtype == expected_dtype
    except Exception as e:
        raise TypeError(f"invalid target data type {expected_dtype}") from e

In [6]:
matrix = np.zeros((3,4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
def init_array(shape,value=0):
    """
    Initialize a NumPy array with a specified shape and fill it with a given value.

    Parameters:
    shape (tuple): The shape of the array to be created.
    value (scalar): The value to fill the array with.

    Returns:
    numpy.ndarray: A new NumPy array of the specified shape filled with the given value.
    """
    return np.full(shape, value)

In [12]:
zeros = init_array((3, 4))
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
def init_weights(n_features , method = 'zeros' , seed = None):
    """
    Initialize weights for a machine learning model based on the specified method.

    Parameters:
    n_features (int): The number of features (input dimensions).
    method (str): The method to initialize weights. Options are 'zeros', 'ones', or 'random'.

    Returns:
    numpy.ndarray: An array of initialized weights.
    """
    if not isinstance(n_features, int) or n_features <= 0:
        raise ValueError("n_features must be a positive integer.")
    if method == 'zeros':
        return np.zeros(n_features)
    elif method == 'ones':
        return np.ones(n_features)
    elif method == 'random':
        if seed is not None:
            np.random.seed(seed)
        return np.random.rand(n_features) *0.01

       
    else:
        raise ValueError("Invalid method. Choose from 'zeros', 'ones', or 'random'.")

In [30]:
initial_weights = init_weights(10, method='random' , seed=20000)
initial_weights

array([0.00392924, 0.00861439, 0.00276146, 0.00181115, 0.00077073,
       0.00783972, 0.00361966, 0.00426006, 0.0032163 , 0.0060676 ])

In [31]:
I = np.identity(3, dtype=float)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.random((3,4))

array([[0.26744361, 0.77750883, 0.22349579, 0.09310093],
       [0.74469988, 0.60899924, 0.8604736 , 0.92272928],
       [0.45842091, 0.28621439, 0.71432774, 0.97226174]])

In [ ]:
np.random.randint(0,11,(5,5)) 
#smallest integer in the range is 0 and the largest integer in the range is 10

array([[ 6,  0,  6, 10, 10],
       [ 8,  0,  8,  1,  2],
       [ 3,  5,  5,  9,  3],
       [ 9,  9,  9,  2,  1],
       [ 1,  8,  9,  2,  3]])

In [34]:
a = ["osama", "ahmed", "mohamed"]
np.random.choice(a, size=(3,5))

array([['ahmed', 'osama', 'osama', 'mohamed', 'ahmed'],
       ['mohamed', 'ahmed', 'osama', 'osama', 'osama'],
       ['ahmed', 'osama', 'osama', 'ahmed', 'ahmed']], dtype='<U7')

In [4]:
mat1 = np.ones((3,4))
mat2 = np.zeros((3,4))

np.savez('file.npz', ones=mat1, zeros=mat2)

In [5]:
with np.load('file.npz') as data:
    ones_array = data['ones']
    zeros_array = data['zeros']

In [7]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
m1 = np.array([[1,2,3],[0,0,0]])
m2 = np.array([[4,5,6],[1,1,1]])

In [10]:
new_mat = np.vstack((m1,m2))
new_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [1, 1, 1]])

In [12]:
new_mat = np.hstack((m1,m2))
new_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [8]:
v1 = np.array([1,2,3,4,5,0])
print(np.any(v1>=1))
print(np.all(v1>=1))
print(np.all(v1>=0))

True
False
True

In [ ]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

print(np.isclose(v1, v2 , atol = 1))

#Compare two arrays element-wise and return a boolean array indicating whether each pair of elements is close to each other within a specified tolerance. The function takes two input arrays and an optional absolute tolerance parameter (atol) that defines the maximum allowed difference between corresponding elements for them to be considered close.

[ True  True False  True False]

In [12]:
print(np.allclose(v1, v2 , atol = 1))

False

In [13]:
v= np.array([2,4,3,4,10])
condition = v>=4
print(condition)

[False  True False  True  True]

In [15]:
v= np.array([2,4,3,4,10])
condition = v>=4
v[condition] = -1
print(v)
# what matches the condition will be replaced with -1, and the rest of the elements will remain unchanged.

[ 2 -1  3 -1 -1]

In [16]:
v= np.array([2,4,3,4,10])
condition = v>=4
new_arr = np.where(condition, -1, v)
print(new_arr)

[ 2 -1  3 -1 -1]

In [18]:
v1 = np.array([1, 4, 5])
c=2
summation = v1 + c
multiplication = v1 * c
print(summation)
print(multiplication)

[3 6 7]
[ 2  8 10]

In [19]:
[[1,0,0,0,0,0,0,0],
 [0,0,0,0,0,0,0,0],
 [0,0,0,0,0,0,0,0]]

[[1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]

---

---

# Pandas

In [20]:
import pandas as pd

In [26]:
s =  pd.Series([1,2 , 3, 4 , 5, 6, 8] , index = ['a', 'b', 'c', 'd', 'e', 'f', 'g'])
print(s)

a    1
b    2
c    3
d    4
e    5
f    6
g    8
dtype: int64

In [33]:
data = [[1,44,"abc"],[2,55,"def"],[3,66,"ghi"]]
df = pd.DataFrame(data , columns = ['col1', 'col2', 'col3'])
df

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi

In [36]:
data = {'col1' : [1,2,3,4] , 'col2' : [44,55,66 , 77] , 'col3' : ["abc", "def", "ghi", "jkl"]}
df = pd.DataFrame(data)
df

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    77  jkl

In [37]:
display(data)

{'col1': [1, 2, 3, 4],
 'col2': [44, 55, 66, 77],
 'col3': ['abc', 'def', 'ghi', 'jkl']}

In [38]:
columns=df.columns
columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [40]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [41]:
index = ["r1", "r2", "r3", "r4"]
df.index = index
display(df)

    col1  col2 col3
r1     1    44  abc
r2     2    55  def
r3     3    66  ghi
r4     4    77  jkl

In [42]:
df.dtypes

col1    int64
col2    int64
col3      str
dtype: object

In [45]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]
 
data = {'col1':[1,2,3,4],
        'col2':[444,555,666,444],
        'col3':['abc','def','ghi','xyz']}
df = pd.DataFrame(data)
df
df['col3'].dtype

In [46]:
df [ 'col1']

0    1
1    2
2    3
3    4
Name: col1, dtype: int64

In [47]:
df["col1"] =df["col1"].astype(float)

In [48]:
df

   col1  col2 col3
0   1.0   444  abc
1   2.0   555  def
2   3.0   666  ghi
3   4.0   444  xyz

In [50]:
cols  = ['col1', 'col2']
df[cols] = df[cols].astype(f'category')
df

  col1 col2 col3
0  1.0  444  abc
1  2.0  555  def
2  3.0  666  ghi
3  4.0  444  xyz

In [51]:
df.dtypes

col1    category
col2    category
col3         str
dtype: object

In [53]:
df.describe(include='all')

        col1  col2 col3
count    4.0     4    4
unique   4.0     3    4
top      1.0   444  abc
freq     1.0     2    1

In [55]:
df.describe(include='category')

        col1  col2
count    4.0     4
unique   4.0     3
top      1.0   444
freq     1.0     2

In [56]:
df['col1'].unique

<bound method Series.unique of 0    1.0
1    2.0
2    3.0
3    4.0
Name: col1, dtype: category
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]>

In [57]:
df['col1'].nunique

<bound method IndexOpsMixin.nunique of 0    1.0
1    2.0
2    3.0
3    4.0
Name: col1, dtype: category
Categories (4, float64): [1.0, 2.0, 3.0, 4.0]>

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      category
 1   col2    4 non-null      category
 2   col3    4 non-null      str
dtypes: category(2), str(1)
memory usage: 228.0 bytes

In [61]:
df ['col3'].value_counts()

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [63]:
x = df['col2'].value_counts()
print(type(x))

<class 'pandas.Series'>